CPUCC       = gcc 
CPPFLAGS    = -O3
DEFS        = 
INCLUDES    = 
LIBDIR      =    
LIBS        = -lm
LINK        = $(LIBDIR) $(LIBS)
COMPILE     = $(CPUCC) $(DEFS) $(INCLUDES) $(CPPFLAGS)

all:   
	$(COMPILE)  main-n-bodfdies.c $(LINK)  -o n-bodies


clean:
	rm n-bodies
